CGPT/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
	path('CGPT/', views.query_view, name='query_view'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup')
]

config/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
    path('CGPT/', include('CGPT.urls')),
]

pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:question_id>/', views.detail, name = 'detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name = 'answer_create'),
    path('question/create/',views.question_create,name = 'question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

#test last please

common/models.py
from django.db import models

# Create your models here.

pybo/models.py
from tkinter.ttk import Treeview

from django.db import models
from django.contrib.auth.models import User

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    
    class Meta:
        db_table = 'answer_tb'

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields=("username","password1","password2","email")

pybo/forms.py
from django import forms
from pybo.models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']

        labels = {
            'subject' : '제목',
            'content' : '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content' : '답변 내용',
        }

common/views.py
from django.contrib.auth import authenticate, logout, login
from django.shortcuts import render, redirect
from .forms import UserForm

def logout_view(request):
    logout(request)
    return redirect('index')

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password = raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form' : form})

pybo/views.py
from importlib.resources import contents

from django.contrib.auth import login
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Question, Answer
from .forms import QuestionForm, AnswerForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q

def index(request):
    page = request.GET.get('page', 1)
    kw = request.GET.get('kw', '')
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제 목 검 색
            Q(content__icontains=kw) |  # 내 용 검 색
            Q(answer__content__icontains=kw) |  # 답 변 내 용 검 색
            Q(author__username__icontains=kw) |  # 질 문 글 쓴 이 검 색
            Q(answer__author__username__icontains=kw)  # 답 변 글 쓴 이 검 색
        ).distinct()
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    context = {'question_list' : page_obj}
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question' : question}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question' : question, 'form' : form}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form' : form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request,'수정 권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수 정 일 시 저 장
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request,'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request,'삭제 권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request,'수정 권한이 없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)
    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('pybo:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer,'form': form}
    return render(request,'pybo/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request,'삭제 권한이 없습니다')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

templates/CGPT.html
<!-- query.html -->
<html>
<head>
	<title>Query</title>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.0/dist/js.cookie.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">
	<script>
		$(document).ready(function() {
			// Send the form on enter keypress and avoid if shift is pressed
			$('#prompt').keypress(function(event) {
				if (event.keyCode === 13 && !event.shiftKey) {
					event.preventDefault();
					$('form').submit();
				}
			});
			$('form').on('submit', function(event) {
				event.preventDefault();
			// get the CSRF token from the cookie
			var csrftoken = Cookies.get('csrftoken');

			// set the CSRF token in the AJAX headers
			$.ajaxSetup({
				headers: { 'X-CSRFToken': csrftoken }
			});
				// Get the prompt
				var prompt = $('#prompt').val();
				var dateTime = new Date();
				var time = dateTime.toLocaleTimeString();
				// Add the prompt to the response div
				$('#response').append('<p>('+ time + ') <i class="bi bi-person"></i>: ' + prompt + '</p>');
				// Clear the prompt
				$('#prompt').val('');
				$.ajax({
					url: '/CGPT/CGPT/',
					type: 'POST',
					data: {prompt: prompt},
					dataType: 'json',
					success: function(data) {
						$('#response').append('<p>('+ time + ') <i class="bi bi-robot"></i>: ' + data.response + '</p>');
					}
				});
			});
		});
	</script>
</head>
<body>
	<a class = "btn btn-primary m-3" href="{% url 'pybo:index' %}">Pybo</a>
	<div class="container p-3">
		<h3>ChatGPT Clone</h3>
		<div class="mb-3">
			<form method="post">
				{% csrf_token %}
				<label for="prompt" class="form-label"><strong>Prompt: </strong></label>
				<textarea class="form-control" type="textarea" id="prompt" name="prompt" rows="3"></textarea>
				<br>
				<button class="btn btn-primary" type="submit">Submit</button>
			</form>
		</div>
		<br>
		<div class="mb-3">
			<h6>Response:</h6>
			<div class="container border overflow-auto h-50" id="response"></div>
		</div>
	</div>
</body>
</html>

templates/base.html
{% load static %}
<!doctype html>
<html lang = "ko">
<head>
    <meta charset="UTF-8">
    <meta name = "viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello Pybo</title>
</head>
<body>
    {% include "navbar.html" %}
    <!-- Basic template -->
    {% block content %}
    {% endblock %}
    <script src = "{% static 'bootstrap.min.js' %}"></script>
    <!-- JS -->
    {% block script %}
    {% endblock %}
</body>
</html>

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class ="container my-3">
    <form method = "post" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name = 'next' value="{{ next }}">
        {% include "form_errors.html" %}
        <div class = "mb-3">
            <label for ="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
            value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id = "password"
            value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class = "btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends 'base.html' %}
{% block content %}
<div class = "container my-3">
    <form method = 'post' action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include 'form_errors.html' %}
        <div class="mb-3">
            <label for="username"> 사 용 자 이 름 </label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1"> 비 밀 번 호 </label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2"> 비 밀 번 호 확 인 </label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email"> 이 메 일 </label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary"> 생 성 하 기 </button>
    </form>

</div>
{% endblock %}

templates/form_errors.html
<!-- 필 드 오 류 와 넌 필 드 오 류 를 출 력 한 다.-->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필 드 오 류-->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌 필 드 오 류-->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<nav class = "navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class = "container-fluid">
        <a class = "navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class = "navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class = "nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    <a class ="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/pybo/answer_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답 변 수 정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label"> 답 변 내 용 </label>
            <textarea class="form-control" name="content" id="content" rows="10">
                {{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary"> 저 장 하 기 </button>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}

<div class = "container my-3">
    <!-- message 표 시-->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class = "border-bottom py-2">{{question.subject}}</h2>
    <div class = "card my-3">
        <div class = "card-body">
            <div class = "card-text" style="white-space : pre-line">{{question.content}}</div>
            <div class = "d-flex justify-content-end">
                {% if question.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ question.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.author.username }}</div>
                    <div>{{ question.create_date }}</div>
            </div>
        </div>
            <div class ="my-3">
                {% if request.user == question.author %}
                <a href="{% url 'pybo:question_modify' question.id %}"
                   class="btn btn-sm btn-outline-secondary"> 수 정 </a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'pybo:question_delete' question.id %}"> 삭 제 </a>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class = "border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class = "card my-3">
        <div class = "card-body">
            <div class = "card-text" style="white-space : pre-line">{{answer.content}}</div>
            <div class = "d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ answer.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                {% if request.user == answer.author %}
                <a href="{% url 'pybo:answer_modify' answer.id %}"
                   class="btn btn-sm btn-outline-secondary"> 수 정 </a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                   data-uri="{% url 'pybo:answer_delete' answer.id %}"> 삭 제 </a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}

    <!-- 답변 등록 -->
    <form action="{% url 'pybo:answer_create' question.id %}" method = "post" class = "my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class = "alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 end -->
        <div class = "mb-3">
            <label for="content" class = "form-label">답변 내용</label>
            <textarea {% if not user.is_authenticated %} disabled {% endif %}
                    name = "content" class = "form-control"id="content" rows="10">
            </textarea>
        </div>
        <input type="submit" value="답변 등록" class = "btn btn-primary">
    </form>
</div>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
    const delete_elements = document.getElementsByClassName("delete");
    Array.from(delete_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm(" 정말로 삭제하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });
</script>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class = "container">
    <h5 class = "my-3 border-bottom pb-2">질 문 등 록</h5>
    <form method = "post">
        {% csrf_token %}
        <!--오류표시 start-->
        {% if form.errors %}
        <div class = "alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!--오류표시 end-->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class = "form-control" name = "subject" id = "subject"
            value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class = "mb-3">
            <label for="content" class = "form-label">내용</label>
            <textarea class="form-control" name="content" id = "content"
            rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class = "btn btn-primary">저 장 하 기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<div class = "container my-3">
    <div class="row my-3">
        <div class="col-2">
            <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
        </div>
        <div class="col-3">
            <a href="/CGPT/CGPT" class="btn btn-primary">GPT</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search"> 찾 기 </button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr class="text-center table-dark">
                <th>번호</th>
                <th style="width:50%"> 제 목 </th>
                <th> 글 쓴 이 </th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
            {% if question_list %}
            {% for question in question_list %}
            <tr class="text-center">
                <td>{{question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1}}</td>
                <td class="text-start">
                    <a href="{%url 'pybo:detail' question.id %}">{{question.subject}}</a>
                    {% if question.answer_set.count > 0 %}
                    <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                    {% endif %}
                </td>
                <td>{{ question.author.username }}</td>
                <td>{{ question.create_date }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="4">질문이 없습니다.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    <!-- 페이징 처리 -->
    <ul class="pagination justify-content-center">
        <!--이전 페이지-->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.previous_page_number }}"
               href="javascript:void(0)"> 이 전 </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex ="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5%}
        {% if page_number == question_list.number %}
        <li class = "page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}"
               href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}"
               href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_page_number }}"
               href="javascript:void(0)"> 다 음 </a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징 처리 -->
</div>
<form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
    const page_elements = document.getElementsByClassName("page-link");
    Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
        });
    });
    const btn_search = document.getElementById("btn_search");
    btn_search.addEventListener('click', function() {
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('page').value = 1;
        document.getElementById('searchForm').submit();
    });
</script>
{% endblock %}